### ISSUE TITLE
bad identifier type

### ISSUE THREAD

**Issue by altmannmarcelo** [chop-dbhi/prometheus-sql#1]
Hi there,

I'm trying to run a custom query, but doesn't matter which query I try it always return:

 `Error fetching state: bad identifier type. expected string, got float64`

Does it means I can only have identifier as strings ?

**Comment by bruth** [comment]
That was the original design, but it was an arbitrary decision. I've update the code (c70d835cf2) to supports key value of any type.

**Comment by bruth** [comment]
Let me know if this fixes the issue!

**Comment by altmannmarcelo** [comment]
Hi Brith.
It's working perfectly now. 

Thanks
