### ISSUE TITLE
Problem using prometheus-sql with MS SQL driver

### ISSUE THREAD

**Issue by luisfilipemartins10** [chop-dbhi/prometheus-sql#12]
When I try to run against a MS SQL Database I get this error:
[teste] 2017/05/31 10:28:37 503 Service Unavailable: problem connecting to database: Unable to open tcp connection with host 'localhost:1433': dial tcp [::1]:1433: getsockopt: connection refused
[teste] 2017/05/31 10:28:37 Backing off for 4.06399931s
[teste] 2017/05/31 10:28:41 503 Service Unavailable: problem connecting to database: Invalid tcp port '1433 user=teste database=teste host=ip password=pass': strconv.ParseUint: parsing "1433 user=teste database=teste host=ip password=pass": invalid syntax

Can you provide a valid queries.yml to use with MS SQL driver?

**Comment by bruth** [comment]
Hi @luisfilipemartins10. There was a [recent fix](https://github.com/chop-dbhi/sql-agent/commit/1fcc067fd0cbff636009d2576386c0699f563431) for how the MSSQL params were combined in the sql-agent code base which this depends on. If you are using Docker, make sure the latest version is pulled `docker pull dbhi/sql-agent`.

**Comment by haxorof** [comment]
Hi @luisfilipemartins10 
Was you problems resolved after using the new image published by @bruth on May 31?

Cheers!

**Comment by luisfilipemartins10** [comment]
Yes.

Thank you for the support.
