### ISSUE TITLE
Getting No queries loaded error on startup

### ISSUE THREAD

**Issue by aroch** [chop-dbhi/prometheus-sql#13]
I'm unable to start the prometheus-sql Docker container, I get a 'No queries loaded!' error in the log.

### Steps Taken
- `docker run -d --name sqlagent dbhi/sql-agent` - container started properly.
- I've created a queries.yml file in current directory (I tried also using the example-queries.yml file) and i'm mounting it to the container.
- `docker run --name prometheus-sql -p 8080:8080 -v queries.yml:/queries.yml --link sqlagent:sqlagent dbhi/prometheus-sql` - container fails to start with the 'No queries loaded!' error.

I verified with a YAML validator that my yml file is valid.
What am I missing?

**Comment by haxorof** [comment]
Hi @aroch,

Based on the information you have given I suspect it is the volume mapping which is incorrectly defined in the docker run command.

Try to change volume mapping of queries file to: `${PWD}/queries.yml:/queries.yml`

If you are not in the same directory while starting the container then write the absolute path to the file instead.

Let me know if it helped you to move forward!

**Comment by haxorof** [comment]
Please reopen if you still have problem.
Cheers!
