### ISSUE TITLE
Change releases to tar.gz instead of zip

### ISSUE THREAD

**Issue by haxorof** [chop-dbhi/prometheus-sql#16]
In for example several very simple Linux installation unzip is not provided out-of-the-box which will required additional steps to install unzip. Also handling zip in combination with curl is not possible either. Delivering tar.gz would allow users which cannot use the Docker version of prometheus-sql to just do this:
```shell
curl -SL https://github.com/chop-dbhi/prometheus-sql/releases/download/1.1.0/prometheus-sql-linux-amd64.tar.gz | tar -xzvC /opt/prometheus-sql
```

Either change all releases to tar.gz or just leave Windows release as zip because it does not have native support for tar.gz.

@bruth: Does this change cause problems in the way you use prometheus-sql today? any thoughts on this?

**Comment by haxorof** [comment]
When #18 is fixed then it is just a matter of format for those which cannot use Docker. Currently releases are downloaded when the prometheus-sql images is built at Docker Hub.

**Comment by bruth** [comment]
I agree keeping `.zip` for the Windows build and changing the others.
