### ISSUE TITLE
Automatic tagging of builds in Docker Hub

### ISSUE THREAD

**Issue by haxorof** [chop-dbhi/prometheus-sql#21]
When a release of prometheus-sql is done no tag is created for that in Docker Hub. Basically if non-compatible changes are introduced then it will not be possible to revert back to for example version 1.1.0.

As written in this post below it is possible to easily get versions to the builds in Docker Hub as soon as you tag in Github:
https://stackoverflow.com/a/44796846

@bruth: Possible to fix?

Configuration basically looks like this:

| Type     | Name                                        | Dockerfile Location | Docker Tag Name |
|---------|-----------------------------------|----------------------|-----------------|
| Branch | master                            | /                   | latest          |
| Tag    | /^([0-9]+)\.([0-9]+)\.([0-9]+)$/ | /                   | {\1}            |
| Tag    | /^([0-9]+)\.([0-9]+)\.([0-9]+)$/ | /                   | {\1}.{\2}       |
| Tag    | /^([0-9]+)\.([0-9]+)\.([0-9]+)$/ | /                   | {\1}.{\2}.{\3}  |

**Comment by bruth** [comment]
I updated the Docker hub build settings.

**Comment by haxorof** [comment]
Great! Then lets see if some tagged build happens the next time a new tag is pushed to Github :octocat:.
