### ISSUE TITLE
Tolerate single-file parsing errors when loading a directory of configuration files

### ISSUE THREAD

**Issue by andybrown668** [chop-dbhi/prometheus-sql#27]
Current functionality exits with an error if even one file in a configuration folder is invalid. 
I'd like the option to tolerate errors so other queries can run.

**Comment by andybrown668** [comment]
I have this coded up so I could submit a PR and push the branch if you like

**Comment by bruth** [comment]
Please do!

**Comment by andybrown668** [comment]
here's the PR - https://github.com/chop-dbhi/prometheus-sql/pull/28
