### ISSUE TITLE
cant connect to postgres

### ISSUE THREAD

**Issue by pytker** [chop-dbhi/prometheus-sql#34]
When i try execute sql query via prometheus-sql i get the error.

> 503 Service Unavailable: problem connecting to database: pq: SSL is not enabled on the server

I cant find how to disable to use ssl in prometheus-sql.

**Comment by pytker** [comment]
It works after added sslmode: disable to datasource properties. Can you add this information in documentation?

**Comment by bruth** [comment]
Hi @pytker. You are correct, all database-specific options can be provided in the [database connection options passed off to sql-agent](https://github.com/chop-dbhi/sql-agent#connection-options).

I opened a PR (#35) which adds an FAQ section.
