### ISSUE TITLE
Requesting help for connecting to Oracle Database

### ISSUE THREAD

**Issue by kevinekw** [chop-dbhi/prometheus-sql#47]
Hi,

Thank you for providing such an awesome tool!

I am quite new to dockers and I was hoping for some guidance. Currently I am trying to connect prometheus-sql with an Oracle Database. Currently I have 2 questions:

1. What would be the name of the driver to connect to a Oracle Database? I have it as **odbc** but it is most likely wrong..
![image](https://user-images.githubusercontent.com/24504968/39284444-9bac27ca-4956-11e8-9258-d1dad9fd9a08.png)

2. How can I check the status of the query (If it ran successfully or failed). I went to localhost:8080/metrics but came back to me as **This site can't be reached**.

Thank you so much!

Regards,
Kevin

**Comment by bruth** [comment]
Hi @kevinekw. Here are the [list of driver names](https://github.com/chop-dbhi/sql-agent/blob/master/driver.go#L290-L300). So `oracle` is what you want.

You can see in the [docker-compose](https://github.com/chop-dbhi/prometheus-sql/blob/master/docker-compose.yml) file that the port is exposed so it should resolve. Are you using Compose or running contains using `docker run`?

**Comment by kevinekw** [comment]
Thanks Bruth.

I am using docker run to run the containers:

docker run -d \
  --name prometheus-sql \
  -p 8080:8080 \
  -v ${PWD}/queries.yml:/queries.yml \
  --link sqlagent:sqlagent \
  dbhi/prometheus-sql \
  -service http://sqlagent:5000 \

I am missing the prometheus-sql.yml file. Would you be able to advice what should be in the prometheus-sql.yml file?

Sorry for all these super basic questions.. I'm still trying to wrap my head around this.

**Comment by bruth** [comment]
Here are examples of config and query files: https://github.com/chop-dbhi/prometheus-sql/tree/master/examples

**Comment by kevinekw** [comment]
Thanks bruth :)
* I'll mark it as close.
