### ISSUE TITLE
How to add help and type fields in metrics

### ISSUE THREAD

**Issue by Saidalavi** [chop-dbhi/prometheus-sql#48]
Hi,
How can we provide our own help text and type in the metrics. Currently the type is coming as gauge and help coming as Result of an SQL query. We tried help and type, but its not reflecting. Can you please provide a solution.

Thanks..

**Comment by haxorof** [comment]
Hi,
Today this is not possible with prometheus-sql. However, what could be implemented is to have a "description" per query which can be displayed as help under the metrics endpoint.

Cheers!

**Comment by pschou** [comment]
I've added this feature in pull request #66
