### ISSUE TITLE
Docker image not built after commit

### ISSUE THREAD

**Issue by haxorof** [chop-dbhi/prometheus-sql#58]
Seems that the build system on Docker hub did not trigger when commit was done on master. 

@bruth Can you have a look at that in Docker hub to see if it still have the connections with github.

**Comment by bruth** [comment]
The GH account was disconnected. I set it up again and a building is pending. You should see a new image show up shortly.

**Comment by bruth** [comment]
Confirmed build https://hub.docker.com/layers/dbhi/prometheus-sql/latest/images/sha256-53f29150aca1fc9fef84fdcde8a868f86d0f1619943ef664d859f7dffe5b2f15?context=repo
