### ISSUE TITLE
CLI option -port not working

### ISSUE THREAD

**Issue by mainiak** [chop-dbhi/prometheus-sql#84]
Hello.

I tested against current (literally) latest docker image (no version?) and previous 1.4.1 and when provided ie. `-port 9000` doesn't work.

I tried to change order how I provide arguments, but order of arguments wasn't the reason. Other CLI (-config, -queries, -service) work.

I tried even looking at source code and there doesn't seem anything wrong with it.

```
/bin/docker run \
--rm \
--name prometheus_sql \
-p 9000:9000 \
-v /data/prometheus_sql:/data \
dbhi/prometheus-sql:1.4.1 \
-port 9000 \
-config /data/config.yml \
-queries /data/queries.yml \
-service http://sqlagent:5000
```

^^^ Doesn't work

I found workaround by providing `-e PROMSQL_PORT=9000` to `docker run`.

Because of the work around it is not any high priority issue, but wanted to report anyway.

**Comment by mainiak** [comment]
Might be because how entrypoint works in docker image ... https://github.com/chop-dbhi/prometheus-sql/blob/5d25f92de9390787d8777bcc5e024de38b0f6b2b/docker-entrypoint.sh#L22 🤔

**Comment by haxorof** [comment]
Thanks for reporting. Will fix
